

[build]
  publish   = "dist/"                  # Directory to publish
  command   = "npm install && npm run lint && npm run build"   # Build command
  functions = "functions"              # Functions directory

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

# Automatically generate sitemap.xml at each build
[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    sitemapPath   = "sitemap.xml"
    changefreq    = "daily"
    priority      = 0.5
    trailingSlash = true

[[plugins]]
  package = "@netlify/plugin-minify-html"
  [plugins.inputs]
    minifyJS   = true
    minifyCSS  = true
    minifyHTML = true

[[plugins]]
  package = "@netlify/plugin-zip-it-and-ship-it"
  [plugins.inputs]
    nodeVersion            = "16.x"
    functionsDir           = "functions"
    packageManager         = "npm"
    packageManagerVersion  = "8.x"
    includeFiles           = ["public/**/*", "functions/**/*"]
    excludeFiles           = ["node_modules/**", "public/**/*.map", "functions/**/*.map"]
    includePackageJson     = true
    includePackageLockJson = true

# Security & caching headers (applied to every path)
[[headers]]
  for = "/*"
  Strict-Transport-Security   = "max-age=63072000; includeSubDomains; preload"
  X-Frame-Options             = "DENY"
  X-Content-Type-Options      = "nosniff"
  Referrer-Policy             = "no-referrer-when-downgrade"
  Permissions-Policy          = "geolocation=(), microphone=()"
  Content-Security-Policy     = "default-src 'self'; img-src 'self' https://cdn.example.com; script-src 'self'; style-src 'self';"
  X-XSS-Protection            = "1; mode=block"
  Cache-Control               = "no-cache, no-store, must-revalidate"
  Pragma                      = "no-cache"
  Expires                     = "0"

# Redirects
[[redirects]]
  from     = "/api/*"
  to       = "/.netlify/functions/:splat"
  status   = 200
  force    = true

[[redirects]]
  from     = "/*"
  to       = "/index.html"
  status   = 200
  force    = true

# Environment variables for production
[context.production.environment]
  FB_PAGE_ACCESS_TOKEN     = "$FB_PAGE_ACCESS_TOKEN"
  IG_BUSINESS_ACCOUNT_ID   = "$IG_BUSINESS_ACCOUNT_ID"
  TWITTER_BEARER_TOKEN     = "$TWITTER_BEARER_TOKEN"
  REDDIT_CLIENT_ID         = "$REDDIT_CLIENT_ID"
  REDDIT_CLIENT_SECRET     = "$REDDIT_CLIENT_SECRET"
  REDDIT_USERNAME          = "$REDDIT_USERNAME"
  REDDIT_PASSWORD          = "$REDDIT_PASSWORD"
  PINTEREST_ACCESS_TOKEN   = "$PINTEREST_ACCESS_TOKEN"
  PINTEREST_BOARD_ID       = "$PINTEREST_BOARD_ID"
  SITE_URL                 = "$SITE_URL"
  SUBREDDIT                = "$SUBREDDIT"

[build.processing]
  skip_processing = false

[build.lifecycle]
  post_build = "node scripts/post-build.js"
